#!/bin/bash


PID_FILE="/var/run/wallchd.pid"

if [ -f "$PID_FILE" ]; then
	PID=$(cat /var/run/wallchd.pid 2> /dev/null)
	if [ -d /proc/$PID ]; then
		kill -s SIGUSR1 $PID
		exit 0
	fi
fi
echo "Wallchd daemon not running!" >&2
exit 1
